# Generated by Django 3.2.8 on 2022-02-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220224_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('movieId', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='save',
            name='movieId',
            field=models.IntegerField(),
        ),
    ]
